robot:
  name: openarm
  version: v1.0

  planning_frame: world

  left:
    planning_group: left_arm
    gripper_group: left_gripper
    end_effector: left_ee
    hand_frame: openarm_left_hand
    gripper_joint: openarm_left_finger_joint1

  right:
    planning_group: right_arm
    gripper_group: right_gripper
    end_effector: right_ee
    hand_frame: openarm_right_hand
    gripper_joint: openarm_right_finger_joint1


default_arm: right


arms:

 right:
   group: right_arm
   gripper: right_gripper
   ee_link: openarm_right_hand


 left:
   group: left_arm
   gripper: left_gripper
   ee_link: openarm_left_hand